# Monitor configuration
# This file can be managed by nwg-displays, or edited manually.
# See https://wiki.hyprland.org/Configuring/Monitors/

# Fallback: auto-detect monitor with preferred resolution
monitor = ,preferred,auto,1.6
